name: First Workflow
on: 
  workflow_dispatch: 
  issue_comment:
    types: [created]
jobs:
  first-job:
    if: contains(github.event.comment.body, 'build this please')
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
