name: First Workflow
on: 
  workflow_dispatch: 
  issue_comment:
    created:
      - 'build this please'
jobs:
  first-job:
    if: ${{ github.event.issue.pull_request }} && contains(github.event.issue.comment.body, 'build this please')
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
