name: Protected Workflow Test
on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  Merge-Freeze-Check:
    if: contains(github.event.pull_request.labels.*.name, 'Ready To Merge')
    runs-on: ubuntu-latest
    steps:
      - name: Check if Tested label is applied
        run: |
          echo "Checking if 'Tested' label is applied"
          echo "${{ github.event.pull_request.labels.*.name | join(', ') }}"
          if [[ "${{ github.event.pull_request.labels.*.name | join(', ') }}" == *"Tested"* ]]; then
            echo "Tested label is applied"
          else
            echo "Tested label is not applied"
            if [[ "${{ github.event.pull_request.labels.*.name }}" == *"Testing Required"* ]]; then
              echo "Testing Required label is applied"
            else
              curl \
                -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
                -d '{
                  "labels": ["Testing Required"]
                }'
            fi
            exit 1
          fi
      - name: Check if particular reviewer has approved a change or not
        run: |
          echo "Checking if particular reviewer has approved a change or not"
          echo "${{ github.event.pull_request.requested_reviewers.*.login | join(', ') }}"
          if [[ ${{ github.event.pull_request.requested_reviewers.*.login | join(', ') }} == "octocat" ]]; then
            echo "octocat has approved the change"
          else
            echo "octocat has not approved the change"
            exit 1
          fi
